### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by freshlySqueezedBananas** [relzhong/vue-virtual-keyboard#1]
I can't figure how you use the keyboard nor how you bind it to the inputs. May you please clarify? Ty

**Comment by relzhong** [comment]
We use it as virtual-keyboard for user input in our kiosk mechine. You can use it as vue component. 
`<Keyboard
      debug
      :options="{usePreview: false, stickyShift: false }"
      ></Keyboard>`
And you can find option config in this [doc](https://github.com/Mottie/Keyboard/wiki/Options)

**Comment by thukuwanjiku** [comment]
@relzhong I can't get it to work too. I installed it and imported in app.js

![image](https://user-images.githubusercontent.com/17809323/50073997-8dd50100-01eb-11e9-9393-780787efd36f.png)

Then I'm using it this way

```
<VueVirtualKeyboard
        debug
        v-model="amountTransacted"
        :options="keyboardOptions"
></VueVirtualKeyboard>
```

with options defined as
```
keyboardOptions: {
                    type:"input",
                    layout: "qwerty",
                    alwaysOpen: true,
                    usePreview: false,
                    useWheel: false,
                    stickyShift: false,
                    appendLocally: true,
                    color: "light",
                    updateOnChange: true,
                    initialFocus: true,
                    display: {
                        "accept" : "Save"
                    }
                }

```

Yet I'm getting this warning with nothing rendering
![image](https://user-images.githubusercontent.com/17809323/50074155-16ec3800-01ec-11e9-9d20-a26c72073d31.png)
