### ISSUE TITLE
Detect inputs from an iFrame

### ISSUE THREAD

**Issue by thepepperone** [relzhong/vue-virtual-keyboard#3]
Hi there! This is a very good Virtual Keyboard Library. 
I'm just keen to know how to detect all inputs from in iframe src and calling the Virtual Keyboard on active inputs done in Vue. 

It'd be of great help if we have some demo for this.

**Comment by relzhong** [comment]
This component contain a input html tag, the Virtual Keyboard is binding to the inside input tag. So far it doesn't support self defined input tag.

**Comment by thepepperone** [comment]
All good. :) Thanks for your response.
