### ISSUE TITLE
Custom element to use as input

### ISSUE THREAD

**Issue by emkeythekeyem** [relzhong/vue-virtual-keyboard#4]
I see that when i initialize the component it automatically creates

 `<input class="keyboard-wrapper" aria-haspopup="true" role="textbox">` 

Can i specify in the options the custom input that will trigger the keyboard? Instead of it to be automatically created?

![Immagine](https://user-images.githubusercontent.com/16360132/60675849-a81bb700-9e7d-11e9-8966-4a1e3f7b0ffd.png)

Thanks

**Comment by relzhong** [comment]
You can‘t directly use input tag, because inside component i use Jquery to bind input or textarea instance. if you want to change style, just use global css to like demo in readme.
